// Demo data shown when TMDB / Google Books API is not configured.
// Movies use the TMDB shape; TV shows use the TMDB TV shape; books use the
// normalized Google Books shape produced by backend/main.py:_normalize_book.
const DEMO_DATA = {
    movies: [
        { id: 157336, title: 'Інтерстеллар', overview: 'Команда дослідників вирушає крізь червоточину у пошуках нового дому для людства.', release_date: '2014-11-05', vote_average: 8.7, genre_ids: [878, 18, 12], poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', _demo: true },
        { id: 278, title: 'Втеча з Шоушенка', overview: 'Бухгалтер Енді опиняється у в\'язниці і знаходить надію в дружбі та винахідливості.', release_date: '1994-09-23', vote_average: 8.7, genre_ids: [18, 80], poster_path: '/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg', _demo: true },
        { id: 155, title: 'Темний лицар', overview: 'Бетмен зіштовхується з Джокером, який сіє хаос у Готемі.', release_date: '2008-07-14', vote_average: 8.5, genre_ids: [28, 80, 18], poster_path: '/qJ2tW6WMUDux911BTUgMe1F6aSe.jpg', _demo: true },
        { id: 27205, title: 'Початок', overview: 'Талановитий злодій, який краде секрети зі снів, отримує неймовірну роботу.', release_date: '2010-07-15', vote_average: 8.4, genre_ids: [28, 878, 12], poster_path: '/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', _demo: true },
        { id: 238, title: 'Хрещений батько', overview: 'Сага про мафіозний клан Корлеоне.', release_date: '1972-03-14', vote_average: 8.7, genre_ids: [18, 80], poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', _demo: true },
        { id: 13, title: 'Форрест Гамп', overview: 'Простий хлопець з Алабами стає учасником ключових подій XX століття.', release_date: '1994-06-23', vote_average: 8.5, genre_ids: [35, 18, 10749], poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', _demo: true },
        { id: 603, title: 'Матриця', overview: 'Хакер Нео дізнається, що його реальність — це симуляція.', release_date: '1999-03-30', vote_average: 8.2, genre_ids: [28, 878], poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', _demo: true },
        { id: 550, title: 'Бійцівський клуб', overview: 'Офісний працівник створює підпільний бійцівський клуб.', release_date: '1999-10-15', vote_average: 8.4, genre_ids: [18, 53], poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', _demo: true },
        { id: 496243, title: 'Паразити', overview: 'Бідна родина обманом влаштовується до багатих, але у плану є секрет.', release_date: '2019-05-30', vote_average: 8.5, genre_ids: [35, 53, 18], poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', _demo: true },
        { id: 546554, title: 'Достати ножі', overview: 'Детектив Бенуа Блан розслідує дивну смерть автора детективів.', release_date: '2019-09-07', vote_average: 7.9, genre_ids: [9648, 35, 80], poster_path: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg', _demo: true },
    ],

    tv: [
        { id: 1396, name: 'Breaking Bad', overview: 'Учитель хімії стає виробником метамфетаміну, щоб забезпечити сім\'ю.', first_air_date: '2008-01-20', vote_average: 8.9, genre_ids: [18, 80], poster_path: '/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', _demo: true },
        { id: 60625, name: 'Rick and Morty', overview: 'Геніальний божевільний дід і його онук подорожують вимірами.', first_air_date: '2013-12-02', vote_average: 8.7, genre_ids: [16, 35, 10765, 10759], poster_path: '/qRiLn4XaCG7DwvSGtDRrNoqcQyq.jpg', _demo: true },
        { id: 66732, name: 'Stranger Things', overview: 'У містечку Гокінс зникає хлопчик і починаються надприродні події.', first_air_date: '2016-07-15', vote_average: 8.6, genre_ids: [18, 9648, 10765], poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', _demo: true },
        { id: 1399, name: 'Game of Thrones', overview: 'Знатні родини змагаються за Залізний трон Семи Королівств.', first_air_date: '2011-04-17', vote_average: 8.4, genre_ids: [10765, 18, 10759], poster_path: '/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg', _demo: true },
        { id: 76479, name: 'The Boys', overview: 'Команда мстивих звичайних людей виступає проти супергероїв-психопатів.', first_air_date: '2019-07-26', vote_average: 8.4, genre_ids: [10759, 18, 10765], poster_path: '/stTEycfG9928HYGEISBFaG1ngjM.jpg', _demo: true },
        { id: 60735, name: 'The Flash', overview: 'Молодий криміналіст отримує надшвидкість після удару блискавки.', first_air_date: '2014-10-07', vote_average: 7.8, genre_ids: [18, 10765, 10759], poster_path: '/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg', _demo: true },
        { id: 1402, name: 'The Walking Dead', overview: 'Шериф прокидається в світі, окупованому зомбі, і шукає вцілілих.', first_air_date: '2010-10-31', vote_average: 8.1, genre_ids: [10759, 18, 10765], poster_path: '/n95Wr9LUZmhWQTZk0loVS8XGcn8.jpg', _demo: true },
        { id: 71712, name: 'The Good Doctor', overview: 'Юний хірург з аутизмом і саванним синдромом приєднується до лікарні.', first_air_date: '2017-09-25', vote_average: 8.5, genre_ids: [18], poster_path: '/6XEWMMU1Qc8tWZkmkY2nHrgnAuf.jpg', _demo: true },
    ],

    books: [
        { id: 'demo-1', title: 'Гаррі Поттер і філософський камінь', authors: ['Дж. К. Роулінг'], description: 'Хлопчик дізнається, що він чарівник, і вирушає до школи Гоґвортс.', categories: ['Fantasy', 'Young Adult'], average_rating: 4.7, year: '1997', poster: 'https://covers.openlibrary.org/b/id/10110415-L.jpg', info_link: 'https://books.google.com/books?id=4lFjAQAACAAJ', _demo: true },
        { id: 'demo-2', title: 'Дюна', authors: ['Френк Герберт'], description: 'Епічна наукова фантастика про планету піщаних червів і магічну спецію.', categories: ['Science Fiction'], average_rating: 4.6, year: '1965', poster: 'https://covers.openlibrary.org/b/id/12631084-L.jpg', info_link: 'https://books.google.com/books?id=ujISBAAAQBAJ', _demo: true },
        { id: 'demo-3', title: 'Майстер і Маргарита', authors: ['Михайло Булгаков'], description: 'Сатанинська хроніка про Москву, любов і силу мистецтва.', categories: ['Fiction', 'Classic'], average_rating: 4.5, year: '1967', poster: 'https://covers.openlibrary.org/b/id/8390365-L.jpg', info_link: 'https://books.google.com/books?id=sx9hAAAAMAAJ', _demo: true },
        { id: 'demo-4', title: '1984', authors: ['Джордж Орвелл'], description: 'Дистопійний роман про тоталітарне суспільство під оком Великого Брата.', categories: ['Fiction', 'Dystopian'], average_rating: 4.4, year: '1949', poster: 'https://covers.openlibrary.org/b/id/8231856-L.jpg', info_link: 'https://books.google.com/books?id=kotPYEqx7kMC', _demo: true },
        { id: 'demo-5', title: 'Маленький принц', authors: ['Антуан де Сент-Екзюпері'], description: 'Філософська казка про дружбу, любов та сенс життя.', categories: ['Fiction', 'Children'], average_rating: 4.6, year: '1943', poster: 'https://covers.openlibrary.org/b/id/8231432-L.jpg', info_link: 'https://books.google.com/books?id=aNsl21yoO5gC', _demo: true },
        { id: 'demo-6', title: 'Sapiens: Коротка історія людства', authors: ['Юваль Ной Харарі'], description: 'Захоплива розповідь про еволюцію Homo sapiens та становлення цивілізації.', categories: ['Non-Fiction', 'History', 'Science'], average_rating: 4.5, year: '2011', poster: 'https://covers.openlibrary.org/b/id/8746889-L.jpg', info_link: 'https://books.google.com/books?id=FmyBAwAAQBAJ', _demo: true },
        { id: 'demo-7', title: 'Атомні звички', authors: ['Джеймс Клір'], description: 'Як невеликі зміни приносять величезні результати.', categories: ['Self-Help', 'Business'], average_rating: 4.7, year: '2018', poster: 'https://covers.openlibrary.org/b/id/8765234-L.jpg', info_link: 'https://books.google.com/books?id=lFhbDwAAQBAJ', _demo: true },
        { id: 'demo-8', title: 'Тіні забутих предків', authors: ['Михайло Коцюбинський'], description: 'Лірична повість про любов і трагедію в Карпатах.', categories: ['Fiction', 'Classic'], average_rating: 4.4, year: '1911', poster: '', info_link: '', _demo: true },
    ],
};
